module.exports.REGISTED_SUCCESS = { code: 200, message: '注册成功' }
module.exports.REGISTED_FAILED = { code: 301, message: '注册失败' }
module.exports.USER_REGISTED = { code: 301, message: '用户已存在' }
module.exports.USER_ACCOUNT_ABNORMALITY = { code: 401, message: '用户账户异常' }
module.exports.NO_USERNAME = { code: 301, message: '请输入用户名' }
module.exports.NO_PASSWORD = { code: 301, message: '请输入密码' }
module.exports.USER_NOT_REGISTERED = { code: 301, message: '用户未注册' }
module.exports.LOGIN_SUCCESS = { code: 200, message: '登录成功' }
module.exports.USERNAME_OR_PASSWORD_ERROR = { code: 301, message: '用户名或密码错误' }
module.exports.NO_TEMPLATE = {}
